#!/bin/bash
# replay ssh logs created by ssh wrapper
[ $DEBUG ] && set -x
[ "$1" = "-h" ] && echo "Usage: $0 logfile [pace_multiplier]" && exit
LOG_DIR=/var/log/ssh/
if	[ -f "$1" ]
then	log="$1"
else	log=$(find $LOG_DIR -name "${1##*/}")
fi

timing=$(find $LOG_DIR -name "${log##*/}*timing")
[ -z "$timing" ] && echo "no timing for $1 found under . or $LOG_DIR" && exit 1
dir=${timing%/*}
file=${timing##*/}
file=${file%.timing}
cp $dir/$file /tmp/$file
awk '{print sqrt($1)," ",$2}' $dir/$file.timing > /tmp/$file.timing
scriptreplay /tmp/$file.timing /tmp/$file $2
rm /tmp/$file*
